spring:
  datasource:
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    database: ${MYSQL_DATABASE}
  
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
